spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.10.240:1522:orcl12c
    username: C##itmscz
    password: itmscz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true